name: Windows Python Workflow

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  run-python:
    runs-on: windows-latest  # Runs on a Windows machine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetches your repository

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set Secret as Environment Variable
        run: echo "SECRET_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: pip install -r requirements.txt  # If dependencies exist

      - name: Run Python Script
        env:
          SECRET_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        run: python src/script.py  # Updated path
